import type { Metadata } from "next";
import { Header } from "@/app/widgets/Header/Header";
import { Sidebar } from "@/app/widgets/Sidebar/Sidebar";
import "./globals.css";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body cz-shortcut-listen="true">
				<div className="antialiased w-screen h-screen overflow-x-hidden overflow-y-auto p-5 min-w-112.5">
					<div className="w-full h-8/100 text-[32px] align-middle m-3">
						<Header />
					</div>

					<div className="flex flex-row w-full justify-between h-[88vh] gap-5">
						<Sidebar />
						{children}
					</div>
				</div>
			</body>
		</html>
	);
}
