import type { Metadata } from "next";
import { Header } from "@/app/widgets/Header/Header";
import { Sidebar } from "@/app/widgets/Sidebar/Sidebar";
import Providers from "./providers";
import "./globals.css";

export const metadata: Metadata = {
	title: "Corp-portal Analytics",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className="relative">
				<Providers>
					<div className="flex flex-col antialiased w-screen h-screen overflow-x-hidden overflow-y-auto gap-3 p-5 min-w-200">
						<div className="w-full h-[8%] text-[32px] align-middle">
							<Header />
						</div>

						<div className="flex flex-row w-full justify-between h-[90%] gap-5">
							<Sidebar />
							{children}
						</div>
					</div>
				</Providers>
			</body>
		</html>
	);
}
