import type { Metadata } from "next";
import { Sidebar } from "@/app/widgets/Sidebar/Sidebar";
import "./globals.css";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className="antialiased w-screen h-screen overflow-x-hidden overflow-y-auto p-5" cz-shortcut-listen="true">
				<div className="text-[32px] align-middle m-3">Header</div>

				<div className="flex flex-row w-full justify-between h-[88vh] gap-5">
					<Sidebar />
					{children}
				</div>
			</body>
		</html>
	);
}
